import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "./fonts"
import AppBar from "@/components/AppBar";

export const metadata: Metadata = {
  title: "Keeping Up With Your Dog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased text-primary`}
      >
        <AppBar />
        {children}
      </body>
    </html>
  );
}
